-- Generated by dataset_to_excel.py
-- Import this after deploy/init_database.sql so root categories 1-5 already exist.

SET NAMES utf8mb4;

INSERT INTO `category` (`id`, `name`, `description`, `sort`, `parent_id`, `practice_mode`, `status`) VALUES
  (1133001, '第二章 世界的物质性及发展规律', 'Imported from 22版《肖秀荣1000题》', 1, 1, 2, 1),
  (2133001, '第八章 习近平新时代中国特色社会主义思想及其历史地位', 'Imported from 22版《肖秀荣1000题》', 1, 2, 2, 1),
  (2133002, '第九章 坚持和发展中国特色社会主义的总任务', 'Imported from 22版《肖秀荣1000题》', 2, 2, 2, 1),
  (2133003, '第十章 “五位一体”总体布局', 'Imported from 22版《肖秀荣1000题》', 3, 2, 2, 1),
  (2133004, '第十一章 “四个全面”战略布局', 'Imported from 22版《肖秀荣1000题》', 4, 2, 2, 1),
  (2133005, '第十二章 全面推进国防和军队现代化', 'Imported from 22版《肖秀荣1000题》', 5, 2, 2, 1),
  (2133006, '第十四章 坚持和加强党的领导', 'Imported from 22版《肖秀荣1000题》', 6, 2, 2, 1),
  (3133001, '第八章 社会主义基本制度在中国的确立', 'Imported from 22版《肖秀荣1000题》', 1, 3, 2, 1),
  (3133002, '第九章 社会主义建设在探索中曲折发展', 'Imported from 22版《肖秀荣1000题》', 2, 3, 2, 1),
  (3133003, '第十一章 中国特色社会主义进入新时代', 'Imported from 22版《肖秀荣1000题》', 3, 3, 2, 1),
  (4133001, '绪论', 'Imported from 22版《肖秀荣1000题》', 1, 4, 2, 1)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `description` = VALUES(`description`),
  `sort` = VALUES(`sort`),
  `parent_id` = VALUES(`parent_id`),
  `practice_mode` = VALUES(`practice_mode`),
  `status` = VALUES(`status`);
